### ISSUE TITLE
Libby setup code impossible to enter

### ISSUE THREAD

**Issue by xSke** [ping/libby-calibre-plugin#14]
On the latest version of the plugin (0.1.9 atm), the 8-digit Libby setup code is impossible to enter, and the input box does not respond to input (even copy/pasting numbers).

If I remove the input mask on the text field (https://github.com/ping/libby-calibre-plugin/blob/main/calibre-plugin/config.py#L230) manually, everything works fine.

I'm using Calibre 6.27 on Windows 10, maybe a Qt version update broke the InputMask functionality somehow?

**Comment by ping** [comment]
Thanks for the report. The input mask has always made the setup code input field a little wonky so I've replaced it with a regex validator.

You probably don't need to but if you wish to give it a test, you can download and install [overdrive-libby-plugin-e3a6397.zip](https://github.com/ping/libby-calibre-plugin/suites/16938786765/artifacts/967669056)
