### ISSUE TITLE
Some titles fail to download

### ISSUE THREAD

**Issue by LoisGNS** [ping/libby-calibre-plugin#15]
Some magazines I've borrowed in Overdrive/Libby will display in the browser, but will not download, except for the cover image and metadata. When I open the containing folder, all that is there is a jpg of the cover. Others are fine. One example is _Essential Guide to Landscape Photography_. Their format, like that of the ones that download successfully, is listed as "Libby Magazine".

**Comment by ping** [comment]
My bad for not properly documenting this properly.

Not all magazines are downloadable. Only magazines that have [readable individual articles](https://help.libbyapp.com/en-us/6215.htm) can be downloaded.

If you don't see an "Article" button near the bottom of the reader in the Libby app, that particular magazine does not support article-mode and cannot be downloaded. These are typically fixed-layout magazines (mainly heavy image-spread type magazines that cover photography, fashion, etc) and cannot be converted to reflowable epubs.

There also isn't a way to identify these magazines until a download is attempted.

_Edited to add:_
The calibre job log will usually tell you what went wrong with downloads. So if you want to know if it's a similar problem or something else, the log is the first place to check.
![job_log](https://github.com/ping/libby-calibre-plugin/assets/104607/4385f489-0594-4306-978d-7f8984c708b7)

**Comment by LoisGNS** [comment]
Thanks. At least I know it wasn't something I did wrong. If there's a way to add a column to the Loans screen where error messages (or brief versions of those) could be inserted, that would let users know there's no point in retrying. Maybe title it "download status" with values like "completed," blank for undownloaded, and "non-downloadable fixed-format"

**Comment by ping** [comment]
Sorry, that's not something I'm interested to add.

The "Hide titles already in library" option filters out loans already downloaded.

Issues with borrowing, downloading, etc, can be checked fairly easily from the calibre jobs interface. And this is not a wildly common scenario, the majority of magazines will download fine.
