### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by p1nkyy** [ping/libby-calibre-plugin#2]
I've asked this in mobileforum but I rarely check there so I might forget to check back, better to ask here: if I have a hold, do I still need to go to Libby and borrow the hold first before it appears in the plugin? Does this plugin only automatically download borrowed books?

**Comment by ping** [comment]
For now, you will have to borrow the hold first in Libby. The next release will allow you to borrow an available hold when it's available.

Just to be clear, the plugin does not _automatically_ download borrowed books. You will have to select the loan and click on Download.

**Comment by p1nkyy** [comment]
OK, thanks for the clarification. Looking forward to the next version.
I still use Overdrive (and I like it better) is it possible to refer the 'View' page to Overdrive site instead of Libby?

**Comment by ping** [comment]
I'll add a View in OverDrive option.

**Comment by p1nkyy** [comment]
While you're at it 😂 sorry for being greedy but it it possible to log in with OD instead of Libby? I am currently adding my library cards to Libby one by one since the plug in requires that but if it's possible that I don't have to do this, it'd be awesome.
Sorry I ask too much

**Comment by ping** [comment]
This plugin can exist only because of the functions that Libby exclusively provides so, sorry, nope on the OD login.

**Comment by p1nkyy** [comment]
No problem, thanks for the answer. Looking forward for future versions!

**Comment by p1nkyy** [comment]
Does the plugin shows books I've borrowed in all the libraries I have that I have input to Libby? Or just the one currently showing as the first library when Libby is opened?

**Comment by ping** [comment]
It should show all. But if you don't see them all, you can redo the setup again after you have finishing setting up Libby on your device.

Go to the plugin configuration, then generate a new code from your device, enter the new code for the plugin, then click OK.

**Comment by ping** [comment]
Version 0.1.4 now supports borrowing available holds and viewing in OverDrive.
