### ISSUE TITLE
I can't enter a setup code to customize the plugin

### ISSUE THREAD

**Issue by bruceberris** [ping/libby-calibre-plugin#22]
No numbers appear when I type numbers in from the Libby setup code.
The keyboard numbers function normally anywhere else.

**Comment by p1nkyy** [comment]
Please add more info. What OS do you use. Which version of Calibre and the plugin.

**Comment by dkuester** [comment]
I have the same issue. I'm on Windows 11, latest patch. I'm using Calibre 7.9, but I've had the same issue in earlier version.

When I try to enter the libby setup code, nothing happens. No numbers appear in the text field, no *** or anything else. When I click on OK, I can confirm that the setup wasn't completed, and it's not a case that the numbers are simply invisible.

I also made sure to use the regular number keys (my Laptop doesn't have a numpad).

**Comment by dkuester** [comment]
I found the reason! If you just randomly click into the text field, you aren't actually at the beginning of the text field. Use use the left arrow-key until you are at the left-most position of the text field. Then you can enter the libby code.

**Comment by bruceberris** [comment]
It's working now as dkuester says.

**Comment by bruceberris** [comment]
Got it.
