### ISSUE TITLE
Title column in Holds tab

### ISSUE THREAD

**Issue by p1nkyy** [ping/libby-calibre-plugin#3]
Title column in Holds tab is very small, can't be resized however I tried. Unlike the Title column in Borrowed tab which is quite ample. Let me know if you need a screenshot?

**Comment by ping** [comment]
Can you try resizing the window?

**Comment by p1nkyy** [comment]
No, that's the thing. Hovering near the border doesn't change my cursor into the usual + sign that meant the column's size is changeable. I tried dragging it as well to no avail.

https://puu.sh/JLSEF/b055893895.png

**Comment by ping** [comment]
I mean resize the whole window, not the column.

**Comment by p1nkyy** [comment]
Ah yeah it works but when it's closed, it returns to the default size.

**Comment by ping** [comment]
Can you check again that the Libby window does not remember the size at all? The window automatically centers when opening, so if you made only small size changes, it may not be obvious. I suggest you test with making the window wider or taller than needed and see if the change persists.

You can also restart calibre in debug and check the logs. You should see at the beginning a line that says something like `Resizing window using saved preferences: (XXX, XXX)`

When you change the size of the Libby window, you should see `Saved new UI height preference: XXX` and/or `Saved new UI width preference: XXX`

```
[overdrive_libby/0.1.5] Resizing window using saved preferences: (784, 364)
...
...
[overdrive_libby/0.1.5] Saved new UI height preference: 429
[overdrive_libby/0.1.5] Saved new UI width preference: 786
[overdrive_libby/0.1.5] Saved new UI height preference: 437
[overdrive_libby/0.1.5] Saved new UI height preference: 442
[overdrive_libby/0.1.5] Saved new UI height preference: 437
```

**Comment by p1nkyy** [comment]
Yeah I have those entries in my Calibre debug log but the window still returned back to the default size once I closed and re-opened it. Do you want a screen recording?
BTW I just noticed that my library cards credential are shown in the Calibre debug log and it's kinda alarming. Is this saved locally? Or to the Calibre server? Can this be hidden? Because if I have issues with other plugin, I might need to attach my Calibre debug log

**Comment by ping** [comment]
Those logs are generated only in debug mode on your machine. They don't get sent anywhere unless you send them yourself.

If you don't launch this plugin, the overdrive_libby logs won't be generated, so it shouldn't be a problem if you're reporting issues with other plugins.

I suspect your issue is a Windows problem. I will have to find a Windows machine to replicate.

**Comment by ping** [comment]
This is fixed for the next release. As a workaround, I suggest you change **_both_** the window **height** and **width**. This should properly save and be restored.

You can also test the fix by downloading and installing the `overdrive-libby-plugin-5e3ada2` artifact from https://github.com/ping/libby-calibre-plugin/actions/runs/5627722047.

**Comment by p1nkyy** [comment]
Hi, thank you for this. It wasn't a hurry but I appreciate you responding and fixing it so soon. Thank you as well for creating this awesome plugin.

EDIT: Just opened it using the latest version and the window stays bigger as I set it last night before I go for the day.
