### ISSUE TITLE
Magazine tab displayed despite hidden

### ISSUE THREAD

**Issue by p1nkyy** [ping/libby-calibre-plugin#5]
I seem to remember it worked before, I have no magazine tab when I select the 'Hide Magazine' but now the Magazine tab keeps being there.

![image](https://github.com/ping/libby-calibre-plugin/assets/7593831/7fe97d5d-426c-4369-80dc-1b613d4500a8)

![image](https://github.com/ping/libby-calibre-plugin/assets/7593831/5dbea09c-47e2-4ddc-9aff-c53abee84d0d)

**Comment by ping** [comment]
You're mistaken. The "Hide Ebooks" and "Hide Magazines" options only affects the loans displayed in the Loans tab.
There is no option to hide any of tabs. If you don't use it, just ignore it. There is no impact at all on syncing unless you've added magazines for monitoring.

https://github.com/ping/libby-calibre-plugin/blob/29ea6ec40a40c24b71b56bfe87b252f575b2becd/README.md?plain=1#L39-L48
